version: 0.2

phases:
  pre_build:
    commands:
      - echo "Install Composer"
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
  build:
    runtime-versions:
      php: 8.1  # Specify the PHP runtime version here
    commands:
      - echo "Running Composer Install"
      - sudo cp .env php_action/
      - cd /var/www/html
      - composer install
      - php php_action/db_connect.php
      # Add any other necessary commands here
  post_build:
    commands:
      # Add any post-build commands here
artifacts:
  files:
    - '**/*'
